"use strict"

module.exports = {
    rules: {
        "vue/array-bracket-newline": "error",
        "vue/array-bracket-spacing": "error",
        "vue/arrow-spacing": "error",
        "vue/block-spacing": "error",
        "vue/brace-style": "error",
        "vue/camelcase": "error",
        "vue/comma-dangle": "error",
        "vue/comma-spacing": "error",
        "vue/comma-style": "error",
        "vue/dot-location": "error",
        "vue/dot-notation": "error",
        "vue/eqeqeq": "error",
        "vue/func-call-spacing": "error",
        "vue/key-spacing": "error",
        "vue/keyword-spacing": "error",
        "vue/max-len": "error",
        "vue/no-empty-pattern": "error",
        "vue/no-extra-parens": "error",
        "vue/no-irregular-whitespace": "error",
        "vue/no-multi-spaces": "error",
        "vue/no-restricted-syntax": "error",
        "vue/no-sparse-arrays": "error",
        "vue/no-unused-vars": "error",
        "vue/no-useless-concat": "error",
        "vue/object-curly-newline": "error",
        "vue/object-curly-spacing": "error",
        "vue/object-property-newline": "error",
        "vue/operator-linebreak": "error",
        "vue/prefer-template": "error",
        "vue/sort-keys": "error",
        "vue/space-in-parens": "error",
        "vue/space-infix-ops": "error",
        "vue/space-unary-ops": "error",
        "vue/template-curly-spacing": "error",
    },
}
